<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	<ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
	<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.24.3" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu.Windows" Version="1.24.3" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.24.3" />
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Cuda" Version="0.12.2" />
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Managed" Version="0.12.2" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LLMLib\LLMLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Girls.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\0228_800x1200_nofix_00010_.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>



</Project>