<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI" Version="9.5.0-preview.1.25262.9" />
    <PackageReference Include="Microsoft.Extensions.AI.AzureAIInference" Version="9.5.0-preview.1.25265.7" />
    <PackageReference Include="Microsoft.Extensions.AI.Ollama" Version="9.5.0-preview.1.25262.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.22.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu.Windows" Version="1.22.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.22.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Cuda" Version="0.7.1" />
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Managed" Version="0.7.1" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RAGLib\RAGLib.csproj" />
  </ItemGroup>

</Project>
