<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Agents.AI" Version="1.10.0" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" Version="1.10.0" />
    <PackageReference Include="Microsoft.AI.Foundry.Local" Version="1.2.1" />
    <PackageReference Include="Microsoft.AI.Foundry.Local.Core" Version="1.2.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.7.0" />
    <PackageReference Include="Microsoft.Extensions.AI.AzureAIInference" Version="10.0.0-preview.1.25559.3" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.7.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.26.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu.Windows" Version="1.26.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.26.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Cuda" Version="0.14.1" />
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Managed" Version="0.14.1" />
    <PackageReference Include="ModelContextProtocol" Version="1.4.0" />
    <PackageReference Include="OllamaSharp" Version="5.4.25" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="10.0.9" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="System.Text.Json" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RAGLib\RAGLib.csproj" />
    <ProjectReference Include="..\SearchEngineLib\SearchEngineLib.csproj" />
  </ItemGroup>

</Project>
